version: '3.8'

services:
  app1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=app-instance-1
      - BIND_PORT=8080
    networks:
      - app-network

  app2:
    build: .
    ports:
      - "8081:8080"
    environment:
      - APP_NAME=app-instance-2
      - BIND_PORT=8080
    networks:
      - app-network

  load_balancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge